BodegasRuizApp/Controllers/ProductoUbicacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BodegasRuizApp.Data;
using BodegasRuizApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace BodegasRuizApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class ProductoUbicacionesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductoUbicacionesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProductoUbicaciones
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ProductoUbicacion.Include(p => p.Producto).Include(p => p.Ubicacion);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProductoUbicaciones/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productoUbicacion = await _context.ProductoUbicacion
                .Include(p => p.Producto)
                .Include(p => p.Ubicacion)
                .FirstOrDefaultAsync(m => m.ProductoUbicacionId == id);
            if (productoUbicacion == null)
            {
                return NotFound();
            }

            return View(productoUbicacion);
        }

        // GET: ProductoUbicaciones/Create
        public IActionResult Create()
        {
            ViewData["ProductoId"] = new SelectList(_context.Producto, "ProductoId", "Nombre");
            ViewData["UbicacionId"] = new SelectList(_context.Ubicacion, "UbicacionId", "UbicacionId");
            return View();
        }

        // POST: ProductoUbicaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoUbicacionId,ProductoId,UbicacionId")] ProductoUbicacion productoUbicacion)
        {
            if (ModelState.IsValid)
            {
                productoUbicacion.ProductoUbicacionId = Guid.NewGuid();
                _context.Add(productoUbicacion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductoId"] = new SelectList(_context.Producto, "ProductoId", "Nombre", productoUbicacion.ProductoId);
            ViewData["UbicacionId"] = new SelectList(_context.Ubicacion, "UbicacionId", "UbicacionId", productoUbicacion.UbicacionId);
            return View(productoUbicacion);
        }

        // GET: ProductoUbicaciones/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productoUbicacion = await _context.ProductoUbicacion.FindAsync(id);
            if (productoUbicacion == null)
            {
                return NotFound();
            }
            ViewData["ProductoId"] = new SelectList(_context.Producto, "ProductoId", "Nombre", productoUbicacion.ProductoId);
            ViewData["UbicacionId"] = new SelectList(_context.Ubicacion, "UbicacionId", "UbicacionId", productoUbicacion.UbicacionId);
            return View(productoUbicacion);
        }

        // POST: ProductoUbicaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProductoUbicacionId,ProductoId,UbicacionId")] ProductoUbicacion productoUbicacion)
        {
            if (id != productoUbicacion.ProductoUbicacionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productoUbicacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoUbicacionExists(productoUbicacion.ProductoUbicacionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductoId"] = new SelectList(_context.Producto, "ProductoId", "Nombre" +
                "" +
                "", productoUbicacion.ProductoId);
            ViewData["UbicacionId"] = new SelectList(_context.Ubicacion, "UbicacionId", "UbicacionId", productoUbicacion.UbicacionId);
            return View(productoUbicacion);
        }

        // GET: ProductoUbicaciones/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productoUbicacion = await _context.ProductoUbicacion
                .Include(p => p.Producto)
                .Include(p => p.Ubicacion)
                .FirstOrDefaultAsync(m => m.ProductoUbicacionId == id);
            if (productoUbicacion == null)
            {
                return NotFound();
            }

            return View(productoUbicacion);
        }

        // POST: ProductoUbicaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var productoUbicacion = await _context.ProductoUbicacion.FindAsync(id);
            _context.ProductoUbicacion.Remove(productoUbicacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoUbicacionExists(Guid id)
        {
            return _context.ProductoUbicacion.Any(e => e.ProductoUbicacionId == id);
        }
    }
}

BodegasRuizApp/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BodegasRuizApp.Data;
using BodegasRuizApp.Models;

namespace BodegasRuizApp.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producto
                .Include(x=>x.Favoritos)
                .Include(p=>p.Precios).ThenInclude(p=>p.Usuario).ThenInclude(p=>p.Ciudad).ThenInclude(p=>p.Provincia)
                .ToListAsync());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoId,Nombre,CantidadTotal,PrecioStd,DiasBarrica,Añada,GradoAlc,Foto,Descripcion")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                producto.ProductoId = Guid.NewGuid();
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProductoId,Nombre,CantidadTotal,PrecioStd,DiasBarrica,Añada,GradoAlc,Foto,Descripcion")] Producto producto)
        {
            if (id != producto.ProductoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var producto = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(Guid id)
        {
            return _context.Producto.Any(e => e.ProductoId == id);
        }
    }
}

BodegasRuizApp/Controllers/UbicacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BodegasRuizApp.Data;
using BodegasRuizApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace BodegasRuizApp.Controllers
{
    [Authorize(Roles = "admin")]
    public class UbicacionesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UbicacionesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Ubicaciones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Ubicacion.OrderBy(u=>u.PosicionX).Include(u=>u.UbicacionProducto).ThenInclude(u=>u.Producto).ToListAsync());
        }

        // GET: Ubicaciones/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ubicacion = await _context.Ubicacion
                .FirstOrDefaultAsync(m => m.UbicacionId == id);
            if (ubicacion == null)
            {
                return NotFound();
            }

            return View(ubicacion);
        }

        // GET: Ubicaciones/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ubicaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UbicacionId,PosicionX,PosicionY")] Ubicacion ubicacion)
        {
            if (ModelState.IsValid)
            {
                ubicacion.UbicacionId = Guid.NewGuid();
                _context.Add(ubicacion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ubicacion);
        }

        // GET: Ubicaciones/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ubicacion = await _context.Ubicacion.FindAsync(id);
            if (ubicacion == null)
            {
                return NotFound();
            }
            return View(ubicacion);
        }

        // POST: Ubicaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("UbicacionId,PosicionX,PosicionY")] Ubicacion ubicacion)
        {
            if (id != ubicacion.UbicacionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ubicacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UbicacionExists(ubicacion.UbicacionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ubicacion);
        }

        // GET: Ubicaciones/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ubicacion = await _context.Ubicacion
                .FirstOrDefaultAsync(m => m.UbicacionId == id);
            if (ubicacion == null)
            {
                return NotFound();
            }

            return View(ubicacion);
        }

        // POST: Ubicaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var ubicacion = await _context.Ubicacion.FindAsync(id);
            _context.Ubicacion.Remove(ubicacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UbicacionExists(Guid id)
        {
            return _context.Ubicacion.Any(e => e.UbicacionId == id);
        }
    }
}

BodegasRuizApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager
@inject UserManager<Usuario> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BodegasRuizApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-secondary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index" style="font-style:italic">
                    <img src="~/img/firma.png" width="30" height="30" class="d-inline-block align-top" alt="logo">
                    BodegasRuiz
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Nosotros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Productos" asp-action="Index">Nuestros Productos</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {

                            <li class="nav-item">
                                <div class="dropdown">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Administrador
                                    </button>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenu2" id="barraAdmin">
                                        <a class="nav-link text-light bg-secondary" asp-area="" asp-controller="Ubicaciones" asp-action="Index">Almacén</a>
                                        <a class="nav-link text-light bg-secondary" asp-area="" asp-controller="ProductoUbicaciones" asp-action="Index">Productos por Ubicación</a>
                                        <a class="nav-link text-light bg-secondary" asp-area="" asp-controller="Home" asp-action="Privacy">Prueba Privacy</a>
                                        <a class="nav-link text-light bg-secondary" asp-area="" asp-controller="" asp-action="">Control Ordenes de compra</a>
                                    </div>
                                </div>
                            </li>
                        }
                        else
                        {

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-light bg-secondary">
        <div class="container">
            &copy; 2020 - BodegasRuiz | Leafletjs | Mapbox | Jquery
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Map.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>