BodegasRuizApp/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BodegasRuizApp.Models
{
    public class Producto
    {
        public Guid ProductoId { get; set; }
        [Required]
        public string Nombre { get; set; }
        public int CantidadTotal { get; set; }
        [Required]
        public double PrecioStd { get; set; }
        [Required]
        [Display(Name = "Dias en barrica")]
        public int DiasBarrica { get; set; }
        [Required]
        [Display(Name = "Año cosecha")]
        public string Añada { get; set; }
        [Required]
        [Display(Name="% alc.")]
        public double GradoAlc { get; set; }
        public string Foto { get; set; }
        [Required]
        [MaxLength(250)]
        [MinLength(30)]
        public string Descripcion { get; set; }
        public List<ProductoUbicacion> ListaProductoUbicacion { get; set; }
        public List<Compra> Compras { get; set; }
        public List<Favorito> Favoritos { get; set; }
        public List<Precio> Precios { get; set; }
    }
}

BodegasRuizApp/Controllers/FavoritosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BodegasRuizApp.Data;
using BodegasRuizApp.Models;

namespace BodegasRuizApp.Controllers
{
    public class FavoritosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FavoritosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Favoritos
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Favorito.Include(f => f.Usuario).Include(f=>f.Producto);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Favoritos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favorito = await _context.Favorito
                .Include(f => f.Usuario)
                .FirstOrDefaultAsync(m => m.FavoritoId == id);
            if (favorito == null)
            {
                return NotFound();
            }

            return View(favorito);
        }

        // GET: Favoritos/Create
        public IActionResult Create()
        {
            ViewData["UsuarioId"] = new SelectList(_context.Users, "Id", "Nombre");
            ViewData["ProductoId"] = new SelectList(_context.Users, "ProductoId", "Nombre");
            return View();
        }

        // POST: Favoritos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FavoritoId,FechaFavorito,FechaDesfavorito,EsFavorito,UsuarioId,ProductoId,Producto")] Favorito favorito)
        {
            if (ModelState.IsValid)
            {
                favorito.FavoritoId = Guid.NewGuid();
                _context.Add(favorito);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Users, "Id", "Nombre", favorito.UsuarioId);
            ViewData["ProductoId"] = new SelectList(_context.Users, "ProductoId", "Nombre", favorito.ProductoId);
            return View(favorito);
        }

        // GET: Favoritos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favorito = await _context.Favorito.FindAsync(id);
            if (favorito == null)
            {
                return NotFound();
            }
            ViewData["UsuarioId"] = new SelectList(_context.Users, "Id", "Id", favorito.UsuarioId);
            return View(favorito);
        }

        // POST: Favoritos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("FavoritoId,FechaFavorito,FechaDesfavorito,EsFavorito,UsuarioId,ProductoId,Producto")] Favorito favorito)
        {
            if (id != favorito.FavoritoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(favorito);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FavoritoExists(favorito.FavoritoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UsuarioId"] = new SelectList(_context.Users, "Id", "Id", favorito.UsuarioId);
            return View(favorito);
        }

        // GET: Favoritos/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var favorito = await _context.Favorito
                .Include(f => f.Usuario)
                .FirstOrDefaultAsync(m => m.FavoritoId == id);
            if (favorito == null)
            {
                return NotFound();
            }

            return View(favorito);
        }

        // POST: Favoritos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var favorito = await _context.Favorito.FindAsync(id);
            _context.Favorito.Remove(favorito);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FavoritoExists(Guid id)
        {
            return _context.Favorito.Any(e => e.FavoritoId == id);
        }
    }
}

BodegasRuizApp/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BodegasRuizApp.Data;
using BodegasRuizApp.Models;

namespace BodegasRuizApp.Controllers
{
    public class ProductosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProductosController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Producto
                .Include(x=>x.Favoritos)
                .Include(p=>p.Precios).ThenInclude(p=>p.Usuario).ThenInclude(p=>p.Ciudad).ThenInclude(p=>p.Provincia)
                .ToListAsync());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Productos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductoId,Nombre,CantidadTotal,PrecioStd,DiasBarrica,Añada,GradoAlc,Foto,Descripcion")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                producto.ProductoId = Guid.NewGuid();
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("ProductoId,Nombre,CantidadTotal,PrecioStd,DiasBarrica,Añada,GradoAlc,Foto,Descripcion")] Producto producto)
        {
            if (id != producto.ProductoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.ProductoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Producto
                .FirstOrDefaultAsync(m => m.ProductoId == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var producto = await _context.Producto.FindAsync(id);
            _context.Producto.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(Guid id)
        {
            return _context.Producto.Any(e => e.ProductoId == id);
        }
    }
}

BodegasRuizApp/Views/Productos/Create.cshtml
@model BodegasRuizApp.Models.Producto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadTotal" class="control-label"></label>
                <input asp-for="CantidadTotal" class="form-control" />
                <span asp-validation-for="CantidadTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioStd" class="control-label"></label>
                <input asp-for="PrecioStd" class="form-control" />
                <span asp-validation-for="PrecioStd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiasBarrica" class="control-label"></label>
                <input asp-for="DiasBarrica" class="form-control" />
                <span asp-validation-for="DiasBarrica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Añada" class="control-label"></label>
                <input asp-for="Añada" class="form-control" />
                <span asp-validation-for="Añada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GradoAlc" class="control-label"></label>
                <input asp-for="GradoAlc" class="form-control" />
                <span asp-validation-for="GradoAlc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BodegasRuizApp/Views/Productos/Delete.cshtml
@model BodegasRuizApp.Models.Producto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioStd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioStd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiasBarrica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiasBarrica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Añada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Añada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GradoAlc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GradoAlc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BodegasRuizApp/Views/Productos/Details.cshtml
@model BodegasRuizApp.Models.Producto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantidadTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioStd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioStd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DiasBarrica)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DiasBarrica)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Añada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Añada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GradoAlc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GradoAlc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BodegasRuizApp/Views/Productos/Edit.cshtml
@model BodegasRuizApp.Models.Producto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Producto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductoId" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CantidadTotal" class="control-label"></label>
                <input asp-for="CantidadTotal" class="form-control" />
                <span asp-validation-for="CantidadTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioStd" class="control-label"></label>
                <input asp-for="PrecioStd" class="form-control" />
                <span asp-validation-for="PrecioStd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiasBarrica" class="control-label"></label>
                <input asp-for="DiasBarrica" class="form-control" />
                <span asp-validation-for="DiasBarrica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Añada" class="control-label"></label>
                <input asp-for="Añada" class="form-control" />
                <span asp-validation-for="Añada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GradoAlc" class="control-label"></label>
                <input asp-for="GradoAlc" class="form-control" />
                <span asp-validation-for="GradoAlc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BodegasRuizApp/Views/Productos/Index.cshtml
@model IEnumerable<BodegasRuizApp.Models.Producto>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<Usuario> SignInManager
@inject UserManager<Usuario> UserManager

@{
    ViewData["Title"] = "Index";
}

<h1>Nuestros vinos</h1>

@if (User.IsInRole("admin"))
{
    <p>
        <a asp-action="Create">Crear nuevo artículo</a>
    </p>
}
<div class="row row-cols-1 row-cols-md-3">
    @foreach (var item in Model)
    {
        <div class="col mb-4 accordion">
            <div class="card text-center" style="width: 18rem;">
                <div class="card-header">
                    <img class="card-img" src="~/img/@item.Foto" data-toggle="collapse" data-target="#demo_@item.ProductoId" alt="@item.Nombre @item.Añada">
                </div>
                <div class="card-body">
                    <h4 class="card-title">@item.Nombre</h4>
                    <h6 class="card-text"> Añada @item.Añada</h6>
                </div>
                <ul class="list-group list-group-flush panel-collapse collapse" id="demo_@item.ProductoId">
                    <li class="list-group-item">Dias en barrica:@item.DiasBarrica</li>
                    <li class="list-group-item">% alcohol: @item.GradoAlc</li>
                    <li class="list-group-item">Cantidad disponible: @item.CantidadTotal</li>
                    <li class="list-group-item">Precio por unidad: @item.PrecioStd</li>
                    @if (User.IsInRole("user") || User.IsInRole("admin"))
                    {
                        <div class="btn-group" role="group" aria-label="Basic example">
                            <a class="btn btn-secondary" type="button" asp-controller="Compras" asp-action="Create" role="button">Comprar</a>
                            <a class="btn btn-secondary" type="button" asp-controller="Favoritos" asp-action="Create" role="button">Favorito</a>
                        </div>
                    }
                </ul>
                @if (User.IsInRole("admin"))
                {
                    <div class="card-body">
                        <a asp-action="Edit" asp-route-id="@item.ProductoId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ProductoId">Details</a> |
                    </div>
                }
            </div>
        </div>
    }
</div>